In [31]:
import pandas as pd
import numpy as np

In [32]:
nrows = 10000000

ndata_columns = 100

# Generate some string categories
ncategories = 10

categories = [pd.util.testing.rands(10) for _ in range(ncategories)]
cats = pd.Series(categories).repeat(nrows / ncategories)

data = {
    'group': cats
}
column_names = ['group']

# Generate some double data
for i in range(ndata_columns):
    name = 'data{}'.format(i)
    data[name] = np.random.randn(nrows)
    column_names.append(name)

%time df = pd.DataFrame(data, columns=column_names)
df.head()

C:\python\lib\site-packages\pandas\util\__init__.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing

CPU times: total: 8.61 s
Wall time: 10.7 s

,group,data0,data1,data2,data3,data4,data5,data6,data7,data8,...,data90,data91,data92,data93,data94,data95,data96,data97,data98,data99
0,GwvA4VERMf,-1.990557,-0.566369,0.150712,-1.191476,-0.563734,-2.026890,-0.933300,1.129240,-1.148071,...,-0.938178,-0.646781,-0.008589,-0.421771,-1.289775,-1.926688,0.686310,-1.452021,1.066108,-1.975004
0,GwvA4VERMf,0.098433,0.284892,-0.454705,-0.674308,0.298234,-0.451653,-0.414814,-0.875727,-0.125435,...,-0.086645,1.197986,1.635670,-0.304908,0.135563,-1.423854,0.476439,-0.833703,0.539781,0.287604
0,GwvA4VERMf,0.963700,0.926052,0.080581,-0.163351,-0.289552,-0.026058,-0.634078,0.856914,1.686633,...,-0.431465,-0.962829,-1.116823,-1.530637,-2.159884,-1.146531,2.181351,1.881312,0.530135,0.090380
0,GwvA4VERMf,0.838603,-0.974956,-0.206524,1.608079,-0.129004,0.795283,-1.715720,0.136106,0.068994,...,-2.116047,1.466438,-0.768148,0.730571,-0.819120,0.068239,1.291170,1.669693,0.243789,-1.841225
0,GwvA4VERMf,-0.643192,1.452770,0.734387,-0.861958,-0.436838,2.587783,-0.936739,-0.880852,1.712057,...,0.990500,-0.465310,-0.505675,-0.284714,0.854298,0.417292,0.082282,-0.479525,-0.849430,0.707852

In [33]:
# pdf = pd.DataFrame(np.random.rand(20000, 20))
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000000 entries, 0 to 9
Columns: 101 entries, group to data99
dtypes: float64(100), object(1)
memory usage: 7.6+ GB

In [34]:
df.to_csv('test_dataset_10M.csv', index=False, header=False)

In [5]:
!ls -l

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [36]:
%time df1 = pd.read_csv('test_dataset_10M.csv')

CPU times: total: 3min 19s
Wall time: 3min 44s

In [40]:
df1.dtypes

GwvA4VERMf              object
-1.9905565498917708    float64
-0.5663685036037228    float64
0.15071160270050485    float64
-1.1914758453348855    float64
                        ...
-1.9266884491100036    float64
0.6863101084121577     float64
-1.4520210343649658    float64
1.0661082691895472     float64
-1.9750042401146253    float64
Length: 101, dtype: object

In [41]:
df1.describe()

,-1.9905565498917708,-0.5663685036037228,0.15071160270050485,-1.1914758453348855,-0.5637336613571323,-2.026890043716739,-0.9332998707088062,1.129239966969344,-1.148070830029692,2.870699049543797,...,-0.9381775000981805,-0.6467807569223669,-0.008588550526084765,-0.4217714930687286,-1.2897753416830227,-1.9266884491100036,0.6863101084121577,-1.4520210343649658,1.0661082691895472,-1.9750042401146253
count,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,...,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06,9.999999e+06
mean,-4.367188e-04,4.269447e-04,6.769691e-04,-2.836968e-04,2.281769e-04,-1.693233e-04,-7.909778e-05,-1.394054e-04,1.370851e-04,-2.310397e-04,...,-1.375317e-04,-1.843315e-04,-3.404717e-04,2.057616e-05,-7.476341e-04,2.796332e-04,-1.277031e-05,-1.248113e-04,1.311457e-04,-3.571539e-04
std,9.999886e-01,9.999075e-01,9.999997e-01,9.997231e-01,1.000091e+00,9.998707e-01,9.999137e-01,9.999205e-01,9.996633e-01,9.999141e-01,...,9.996824e-01,1.000062e+00,1.000148e+00,9.997658e-01,9.999668e-01,1.000403e+00,9.999843e-01,1.000238e+00,9.999649e-01,1.000213e+00
min,-5.356645e+00,-5.014422e+00,-5.266675e+00,-5.522500e+00,-5.557373e+00,-5.459995e+00,-4.978351e+00,-5.056683e+00,-5.625042e+00,-5.346577e+00,...,-5.389585e+00,-5.196143e+00,-5.348391e+00,-5.690287e+00,-5.237489e+00,-5.445565e+00,-5.551515e+00,-5.201482e+00,-5.247954e+00,-4.893781e+00
25%,-6.749302e-01,-6.739686e-01,-6.738623e-01,-6.748667e-01,-6.746584e-01,-6.750858e-01,-6.741883e-01,-6.746227e-01,-6.742941e-01,-6.744870e-01,...,-6.740610e-01,-6.748190e-01,-6.748646e-01,-6.742992e-01,-6.751512e-01,-6.739851e-01,-6.747483e-01,-6.751100e-01,-6.745251e-01,-6.750901e-01
50%,-4.111838e-04,4.149579e-04,2.442255e-04,-3.647398e-04,2.044043e-04,-1.264619e-04,-3.529652e-04,-3.125200e-04,2.265314e-04,-1.047954e-04,...,-3.981949e-04,-2.282846e-04,-1.038335e-04,1.965137e-04,-4.665750e-04,-9.847929e-06,-3.809028e-04,-2.445337e-04,2.836513e-04,-2.881913e-04
75%,6.737834e-01,6.745468e-01,6.749181e-01,6.737922e-01,6.748301e-01,6.742430e-01,6.742580e-01,6.741568e-01,6.741642e-01,6.742288e-01,...,6.743820e-01,6.743412e-01,6.742565e-01,6.743576e-01,6.735058e-01,6.750350e-01,6.744033e-01,6.738191e-01,6.750201e-01,6.740666e-01
max,5.515436e+00,5.179637e+00,5.303497e+00,4.929210e+00,5.210116e+00,6.035384e+00,5.581307e+00,5.230737e+00,5.241324e+00,5.413825e+00,...,5.162343e+00,5.319687e+00,5.528325e+00,4.913294e+00,4.980693e+00,5.368122e+00,5.199563e+00,5.279343e+00,5.249345e+00,5.397696e+00

In [1]:
import findspark
findspark.init()

In [2]:
import os
import sys
import glob

spark_home = 'C:\spark\spark-3.1.3-bin-hadoop3.2'

if 'SPARK_HOME' not in os.environ:
    os.environ['SPARK_HOME'] = spark_home 

SPARK_HOME = os.environ['SPARK_HOME']

sys.path.insert(0,os.path.join(SPARK_HOME,"python"))
for lib in glob.glob(os.path.join(SPARK_HOME, "python", "lib", "*.zip")):
    sys.path.insert(0,lib);

from pyspark import SparkContext
from pyspark.conf import SparkConf
from pyspark.sql import SQLContext
import pyspark
from pyspark.sql import SparkSession

conf=SparkConf()

conf.set("spark.executor.memory", "16g")
conf.set("spark.driver.memory", "16g")
conf.set("spark.driver.maxResultSize", "16g")
conf.set("spark.cores.max", "4")

# sc = SparkContext.getOrCreate(conf)
spark = SparkSession.builder.config(conf=conf).getOrCreate()

# %time df = spark.read.csv("test_dataset.csv",inferSchema =True)
# %time spark_df = spark.read.csv("test_dataset.csv",inferSchema =True)

In [3]:
# spark = SparkSession.builder.getOrCreate()
%time spark_df = spark.read.csv("test_dataset_10M.csv",inferSchema =True)

CPU times: total: 0 ns
Wall time: 2min 6s

In [4]:
test = spark.sql('''select 'spark' as hello''')
test.show()

+-----+
|hello|
+-----+
|spark|
+-----+

In [5]:
# %time spark_df = spark.read.csv("test_dataset.csv",inferSchema =True)

In [6]:
spark_df.dtypes

[('_c0', 'string'),
 ('_c1', 'double'),
 ('_c2', 'double'),
 ('_c3', 'double'),
 ('_c4', 'double'),
 ('_c5', 'double'),
 ('_c6', 'double'),
 ('_c7', 'double'),
 ('_c8', 'double'),
 ('_c9', 'double'),
 ('_c10', 'double'),
 ('_c11', 'double'),
 ('_c12', 'double'),
 ('_c13', 'double'),
 ('_c14', 'double'),
 ('_c15', 'double'),
 ('_c16', 'double'),
 ('_c17', 'double'),
 ('_c18', 'double'),
 ('_c19', 'double'),
 ('_c20', 'double'),
 ('_c21', 'double'),
 ('_c22', 'double'),
 ('_c23', 'double'),
 ('_c24', 'double'),
 ('_c25', 'double'),
 ('_c26', 'double'),
 ('_c27', 'double'),
 ('_c28', 'double'),
 ('_c29', 'double'),
 ('_c30', 'double'),
 ('_c31', 'double'),
 ('_c32', 'double'),
 ('_c33', 'double'),
 ('_c34', 'double'),
 ('_c35', 'double'),
 ('_c36', 'double'),
 ('_c37', 'double'),
 ('_c38', 'double'),
 ('_c39', 'double'),
 ('_c40', 'double'),
 ('_c41', 'double'),
 ('_c42', 'double'),
 ('_c43', 'double'),
 ('_c44', 'double'),
 ('_c45', 'double'),
 ('_c46', 'double'),
 ('_c47', 'double'),
 ('_c48', 'double'),
 ('_c49', 'double'),
 ('_c50', 'double'),
 ('_c51', 'double'),
 ('_c52', 'double'),
 ('_c53', 'double'),
 ('_c54', 'double'),
 ('_c55', 'double'),
 ('_c56', 'double'),
 ('_c57', 'double'),
 ('_c58', 'double'),
 ('_c59', 'double'),
 ('_c60', 'double'),
 ('_c61', 'double'),
 ('_c62', 'double'),
 ('_c63', 'double'),
 ('_c64', 'double'),
 ('_c65', 'double'),
 ('_c66', 'double'),
 ('_c67', 'double'),
 ('_c68', 'double'),
 ('_c69', 'double'),
 ('_c70', 'double'),
 ('_c71', 'double'),
 ('_c72', 'double'),
 ('_c73', 'double'),
 ('_c74', 'double'),
 ('_c75', 'double'),
 ('_c76', 'double'),
 ('_c77', 'double'),
 ('_c78', 'double'),
 ('_c79', 'double'),
 ('_c80', 'double'),
 ('_c81', 'double'),
 ('_c82', 'double'),
 ('_c83', 'double'),
 ('_c84', 'double'),
 ('_c85', 'double'),
 ('_c86', 'double'),
 ('_c87', 'double'),
 ('_c88', 'double'),
 ('_c89', 'double'),
 ('_c90', 'double'),
 ('_c91', 'double'),
 ('_c92', 'double'),
 ('_c93', 'double'),
 ('_c94', 'double'),
 ('_c95', 'double'),
 ('_c96', 'double'),
 ('_c97', 'double'),
 ('_c98', 'double'),
 ('_c99', 'double'),
 ('_c100', 'double')]

In [11]:
# %time final_df = spark_df.toPandas()

In [12]:
# final_df.head()

In [13]:
# final_df.describe()

In [7]:
# spark.conf.set("spark.sql.execution.arrow.enabled", "true")
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

In [8]:
%time final_df1 = spark_df.toPandas()

CPU times: total: 30.4 s
Wall time: 2min 41s

In [10]:
%time final_df1.describe()

CPU times: total: 38 s
Wall time: 38 s

,_c1,_c2,_c3,_c4,_c5,_c6,_c7,_c8,_c9,_c10,...,_c91,_c92,_c93,_c94,_c95,_c96,_c97,_c98,_c99,_c100
count,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,...,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07
mean,-4.369179e-04,4.268880e-04,6.769841e-04,-2.838159e-04,2.281205e-04,-1.695260e-04,-7.919110e-05,-1.392925e-04,1.369702e-04,-2.307526e-04,...,-1.376255e-04,-1.843961e-04,-3.404726e-04,2.053398e-05,-7.477630e-04,2.794405e-04,-1.270168e-05,-1.249565e-04,1.312523e-04,-3.573513e-04
std,9.999887e-01,9.999074e-01,9.999996e-01,9.997231e-01,1.000091e+00,9.998708e-01,9.999137e-01,9.999205e-01,9.996633e-01,9.999145e-01,...,9.996824e-01,1.000062e+00,1.000148e+00,9.997658e-01,9.999668e-01,1.000403e+00,9.999842e-01,1.000238e+00,9.999649e-01,1.000213e+00
min,-5.356645e+00,-5.014422e+00,-5.266675e+00,-5.522500e+00,-5.557373e+00,-5.459995e+00,-4.978351e+00,-5.056683e+00,-5.625042e+00,-5.346577e+00,...,-5.389585e+00,-5.196143e+00,-5.348391e+00,-5.690287e+00,-5.237489e+00,-5.445565e+00,-5.551515e+00,-5.201482e+00,-5.247954e+00,-4.893781e+00
25%,-6.749303e-01,-6.739685e-01,-6.738623e-01,-6.748667e-01,-6.746583e-01,-6.750859e-01,-6.741884e-01,-6.746224e-01,-6.742943e-01,-6.744870e-01,...,-6.740611e-01,-6.748189e-01,-6.748645e-01,-6.742992e-01,-6.751517e-01,-6.739853e-01,-6.747482e-01,-6.751101e-01,-6.745251e-01,-6.750905e-01
50%,-4.113038e-04,4.148065e-04,2.442816e-04,-3.649737e-04,2.043378e-04,-1.265241e-04,-3.530657e-04,-3.124307e-04,2.264540e-04,-1.047852e-04,...,-3.982111e-04,-2.284937e-04,-1.038517e-04,1.965056e-04,-4.670250e-04,-9.857936e-06,-3.808666e-04,-2.445958e-04,2.836853e-04,-2.883857e-04
75%,6.737834e-01,6.745466e-01,6.749181e-01,6.737921e-01,6.748301e-01,6.742429e-01,6.742579e-01,6.741570e-01,6.741641e-01,6.742290e-01,...,6.743820e-01,6.743412e-01,6.742564e-01,6.743576e-01,6.735058e-01,6.750349e-01,6.744037e-01,6.738190e-01,6.750201e-01,6.740666e-01
max,5.515436e+00,5.179637e+00,5.303497e+00,4.929210e+00,5.210116e+00,6.035384e+00,5.581307e+00,5.230737e+00,5.241324e+00,5.413825e+00,...,5.162343e+00,5.319687e+00,5.528325e+00,4.913294e+00,4.980693e+00,5.368122e+00,5.199563e+00,5.279343e+00,5.249345e+00,5.397696e+00

In [14]:
final_df1.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 21 columns):
 #   Column  Dtype
---  ------  -----
 0   _c0     object
 1   _c1     float64
 2   _c2     float64
 3   _c3     float64
 4   _c4     float64
 5   _c5     float64
 6   _c6     float64
 7   _c7     float64
 8   _c8     float64
 9   _c9     float64
 10  _c10    float64
 11  _c11    float64
 12  _c12    float64
 13  _c13    float64
 14  _c14    float64
 15  _c15    float64
 16  _c16    float64
 17  _c17    float64
 18  _c18    float64
 19  _c19    float64
 20  _c20    float64
dtypes: float64(20), object(1)
memory usage: 320.4+ MB

In [15]:
from pyspark.sql.functions import rand

In [26]:
df = spark.range(1 << 28).toDF("id").withColumn("x", rand())

In [27]:
df.printSchema()

root
 |-- id: long (nullable = false)
 |-- x: double (nullable = false)

In [28]:
%time pdf = df.toPandas()

CPU times: total: 10 s
Wall time: 42.3 s

In [29]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268435456 entries, 0 to 268435455
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   id      int64
 1   x       float64
dtypes: float64(1), int64(1)
memory usage: 4.0 GB

In [30]:
%time pdf.describe()

CPU times: total: 15.5 s
Wall time: 15.7 s

                 id             x
count  2.684355e+08  2.684355e+08
mean   1.342177e+08  4.999893e-01
std    7.749064e+07  2.886774e-01
min    0.000000e+00  1.358026e-09
25%    6.710886e+07  2.499842e-01
50%    1.342177e+08  4.999452e-01
75%    2.013266e+08  7.499930e-01
max    2.684355e+08  1.000000e+00